/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
  // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
  id("org.jetbrains.kotlin.jvm").version("1.3.21")

  // Apply the application plugin to add support for building a CLI application.
  application
}

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
}

dependencies {
  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  // Use JLine3 command-line library
  implementation("org.jline:jline-builtins:3.11.0")
  implementation("org.jline:jline-reader:3.11.0")
  implementation("org.jline:jline-terminal:3.11.0")

  // Use the Kotlin test library.
  testImplementation("org.jetbrains.kotlin:kotlin-test")

  // Use the Kotlin JUnit integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
  // Define the main class for the application.
  mainClassName = "testline.ExampleKt"
}

tasks {
  withType<Jar> {
    manifest {
      attributes(mapOf("Main-Class" to application.mainClassName))
    }
  }
}

// vim: se et ts=2 sw=2 number:
